# Generated by Django 5.0.1 on 2024-01-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlist', '0001_initial'),
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='likes', to='track.track'),
        ),
    ]
