# Generated by Django 5.0.1 on 2024-01-17 10:16

import django.utils.timezone
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(default=user.models.User, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('url_audio', models.URLField()),
                ('click_count', models.IntegerField(default=0, editable=False)),
                ('url_cover', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
